server:
  port: 8096

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.72.211:3306/blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zxc123456
  #Redis Config
  redis:
    post: 6379
    host: 139.196.72.211
    database: 0
    jedis:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: -1
        min-idle: 0
    timeout: 1000

thymeleaf:
  cache: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG