server:
  port: 8091

spring:
  application:
    name: blog-eureka
  security:
    user:
      name: ygd
      password: ygd

eureka:
  client:
    service-url:
      defaultZone: http://ygd:ygd@localhost:8091/eureka/
    register-with-eureka: false
